[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
revert_strings = "debug"
ignored_error_codes = [5740, 5574]
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
